import type { Metadata } from "next";
import "./styles/globals.css";
import { Merriweather, Lato } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["700"],
  style:["normal"],
  variable: "--fonte-primaria",
  });

export const lato = Lato({
  subsets: ["latin"],
  weight: ["400","700"],
  style:["normal"],
  variable: "--fonte-secundaria",
  });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${merriweather.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
